services:
  # 1. User Service
  user-service:
    build: ./user-service
    container_name: mdd_user_service
    ports:
      - "8081:8081"                # ผูกพอร์ต เครื่องเรา:พอร์ตในDocker

  # 2. Room Service
  room-service:
    build: ./room-service
    container_name: mdd_room_service
    ports:
      - "8082:8082"
  # 3. Meter Service
  meter-service:
    build: ./meter-service
    container_name: mdd_meter-service
    ports:
      - "8083:8083"                # ผูกพอร์ต เครื่องเรา:พอร์ตในDocker

  # 4. bill-service
  bill-service:
    build: ./bill-service
    container_name: mdd_bill-service
    ports:
      - "8084:8084"

  # 5. Gateway Service
  gateway-service:
    build: ./gateway-service
    container_name: mdd_gateway_service
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - room-service
      - meter-service
      - bill-service

  # 6. RabbitMQ (Message Broker)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: mdd_rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
